"""Balatro package policy registration."""

from games.balatro.aces_dna_hand_policy import install_aces_dna_hand_policy
from games.balatro.aces_scholar_policy import install_aces_scholar_policy
from games.balatro.ankh_presale_policy import install_ankh_presale_policy
from games.balatro.blue_joker_strategy_rules import apply_blue_joker_strategy_rules
from games.balatro.build_health_policy import install_build_health_policy
from games.balatro.card_sharp_strategy_rules import install_card_sharp_strategy_rules
from games.balatro.cash_scoring_support_policy import install_cash_scoring_support_policy
from games.balatro.committed_build_replacement_policy import install_committed_build_replacement_policy
from games.balatro.committed_pack_choice_policy import install_committed_pack_choice_policy
from games.balatro.constellation_strategy_rules import apply_constellation_strategy_rules
from games.balatro.d1_log_resilience_policy import install_d1_log_resilience_policy
from games.balatro.d1_strategy_fit_cache_policy import install_d1_strategy_fit_cache_policy
from games.balatro.deck_growth_pack_policy import install_deck_growth_pack_policy
from games.balatro.early_capacity_policy import install_early_capacity_policy
from games.balatro.five_run_decision_integrity_policy import install_five_run_decision_integrity_policy
from games.balatro.five_run_followup_policy import install_five_run_followup_policy
from games.balatro.five_run_optimization_policy import install_five_run_optimization_policy
from games.balatro.five_run_release_candidate_policy import install_five_run_release_candidate_policy
from games.balatro.five_run_validation_policy import install_five_run_validation_policy
from games.balatro.latest_batch_build_quality_policy import install_latest_batch_build_quality_policy
from games.balatro.latest_batch_no_discard_policy import install_latest_batch_no_discard_policy
from games.balatro.latest_five_run_calibration_policy import install_latest_five_run_calibration_policy
from games.balatro.latest_five_run_relationship_promotions import install_latest_five_run_relationship_promotions
from games.balatro.latest_five_run_resource_metrics import install_latest_five_run_resource_metrics
from games.balatro.latest_five_run_strategy_metrics import install_latest_five_run_strategy_metrics
from games.balatro.log_batch_calibration_policy import install_log_batch_calibration_policy
from games.balatro.mouth_hand_policy import install_mouth_first_hand_policy
from games.balatro.noncash_cash_deployment_policy import install_noncash_cash_deployment_policy
from games.balatro.observatory_planet_policy import install_observatory_planet_policy
from games.balatro.pareidolia_face_policy import install_pareidolia_face_policy
from games.balatro.realized_pivot_policy import install_realized_pivot_policy
from games.balatro.relationship_contract_policy import install_relationship_contract_policy
from games.balatro.safe_pace_blind_skip_patch import install_safe_pace_blind_skip_patch
from games.balatro.safe_pace_optimization_policy import install_safe_pace_optimization_policy
from games.balatro.safe_pace_scope_correction import install_safe_pace_scope_correction
from games.balatro.safe_pace_timeout_patch import install_safe_pace_timeout_patch
from games.balatro.shop_regression_policy import install_shop_regression_policy
from games.balatro.sixth_sense_policy import install_sixth_sense_policy
from games.balatro.strategy_banned_conflict_policy import install_strategy_banned_conflict_policy
from games.balatro.strategy_commitment_hysteresis import install_strategy_commitment_hysteresis
from games.balatro.strategy_conditional_authority_correction import install_strategy_conditional_authority_correction
from games.balatro.strategy_conditional_authority_policy import install_strategy_conditional_authority_policy
from games.balatro.strategy_multi_engine import install_multi_engine_strategy_policy
from games.balatro.strategy_phase_weight_policy import install_strategy_phase_weight_policy
from games.balatro.strategy_relationship_calibration import install_strategy_relationship_calibration
from games.balatro.ten_four_strategy_calibration import install_ten_four_strategy_calibration
from games.balatro.three_run_review_policy import install_three_run_review_policy
from games.balatro.v1_0_0_luchador_policy import install_v1_0_0_luchador_policy
from games.balatro.v1_0_0_policy import install_v1_0_0_policy


apply_blue_joker_strategy_rules()
apply_constellation_strategy_rules()
install_multi_engine_strategy_policy()
install_mouth_first_hand_policy()
install_aces_scholar_policy()
install_pareidolia_face_policy()
install_card_sharp_strategy_rules()
install_d1_log_resilience_policy()
install_log_batch_calibration_policy()
install_shop_regression_policy()
install_three_run_review_policy()
install_strategy_commitment_hysteresis()
install_safe_pace_optimization_policy()
install_safe_pace_timeout_patch()
install_safe_pace_blind_skip_patch()
install_safe_pace_scope_correction()
install_v1_0_0_policy()
install_v1_0_0_luchador_policy()
install_five_run_optimization_policy()
install_five_run_followup_policy()
install_cash_scoring_support_policy()
install_observatory_planet_policy()
install_sixth_sense_policy()
install_early_capacity_policy()
install_relationship_contract_policy()
install_strategy_conditional_authority_policy()
install_strategy_conditional_authority_correction()
install_strategy_phase_weight_policy()
install_strategy_relationship_calibration()
install_ten_four_strategy_calibration()
install_latest_five_run_strategy_metrics()
# Dynamic Walkie+Even and scaled-Throwback promotions belong in the existing
# state-aware relationship resolver, never in private tracker assessment methods.
install_latest_five_run_relationship_promotions()
install_latest_five_run_resource_metrics()
install_strategy_banned_conflict_policy()
install_five_run_release_candidate_policy()
install_five_run_validation_policy()
install_committed_build_replacement_policy()
install_deck_growth_pack_policy()
install_committed_pack_choice_policy()
install_aces_dna_hand_policy()
install_ankh_presale_policy()
install_five_run_decision_integrity_policy()
install_latest_five_run_calibration_policy()
install_latest_batch_no_discard_policy()
# Realized pivot maturity must run before Build Health so candidate transition
# probes see the same buildup/runway gate as the production strategy tracker.
install_realized_pivot_policy()
# Build Health evaluates legal outcomes produced by all earlier safety/retention layers.
install_build_health_policy()
# Latest-batch build-quality pressure runs after Build Health and after committed-build
# protection, so it can relax only the ordinary replacement margin while preserving
# existing legality/protection decisions.
install_latest_batch_build_quality_policy()
# Cash deployment intentionally runs after Build Health so it only spends excess cash
# when the final public-state health assessment says the non-cash build is inadequate.
install_noncash_cash_deployment_policy()
# D1 caching is installed last because it is a semantics-preserving wrapper around
# the final composed strategy-aware hand policy.
install_d1_strategy_fit_cache_policy()
