"""Balatro package policy registration."""

from games.balatro.aces_scholar_policy import install_aces_scholar_policy
from games.balatro.blue_joker_strategy_rules import apply_blue_joker_strategy_rules
from games.balatro.card_sharp_strategy_rules import install_card_sharp_strategy_rules
from games.balatro.constellation_strategy_rules import apply_constellation_strategy_rules
from games.balatro.d1_log_resilience_policy import install_d1_log_resilience_policy
from games.balatro.log_batch_calibration_policy import install_log_batch_calibration_policy
from games.balatro.mouth_hand_policy import install_mouth_first_hand_policy
from games.balatro.pareidolia_face_policy import install_pareidolia_face_policy
from games.balatro.safe_pace_blind_skip_patch import install_safe_pace_blind_skip_patch
from games.balatro.safe_pace_optimization_policy import install_safe_pace_optimization_policy
from games.balatro.shop_regression_policy import install_shop_regression_policy
from games.balatro.strategy_commitment_hysteresis import install_strategy_commitment_hysteresis
from games.balatro.strategy_multi_engine import install_multi_engine_strategy_policy
from games.balatro.three_run_review_policy import install_three_run_review_policy


apply_blue_joker_strategy_rules()
apply_constellation_strategy_rules()
install_multi_engine_strategy_policy()
install_mouth_first_hand_policy()
install_aces_scholar_policy()
install_pareidolia_face_policy()
install_card_sharp_strategy_rules()
install_d1_log_resilience_policy()
install_log_batch_calibration_policy()
install_shop_regression_policy()
install_three_run_review_policy()
install_strategy_commitment_hysteresis()
install_safe_pace_optimization_policy()
install_safe_pace_blind_skip_patch()
