from __future__ import annotations

from types import MappingProxyType

from .strategy import StrategyDefinition


def _normalize(value: str) -> str:
    return "".join(character for character in value.lower() if character.isalnum())


def _names(*values: str) -> frozenset[str]:
    return frozenset(_normalize(value) for value in values)


def _joker_names(*values: str) -> frozenset[str]:
    normalized = {_normalize(value) for value in values}
    return frozenset(
        {
            *normalized,
            *(f"{value}joker" for value in normalized if not value.endswith("joker")),
        }
    )


def _strategy(
    strategy_id: str,
    name: str,
    hand: str | None = None,
    *,
    gold_jokers=(),
    silver_jokers=(),
    bronze_jokers=(),
    banned_jokers=(),
    gold_consumables=(),
    silver_consumables=(),
    bronze_consumables=(),
    banned_consumables=(),
    gold_planets=(),
    silver_planets=(),
    bronze_planets=(),
    banned_planets=(),
    gold_vouchers=(),
    silver_vouchers=(),
    bronze_vouchers=(),
    banned_vouchers=(),
    preferred_suits=(),
    preferred_enhancements=(),
    preferred_seals=(),
    preferred_editions=(),
    preferred_ranks=(),
    face_mode=None,
    any_suit_concentration=False,
    required_jokers=(),
    minimum_positive_jokers=0,
    entry_evidence_cap=1.0,
) -> StrategyDefinition:
    return StrategyDefinition(
        strategy_id=strategy_id,
        name=name,
        primary_hands=(() if hand is None else (hand,)),
        gold_jokers=_joker_names(*gold_jokers),
        silver_jokers=_joker_names(*silver_jokers),
        bronze_jokers=_joker_names(*bronze_jokers),
        banned_jokers=_joker_names(*banned_jokers),
        gold_consumables=_names(*gold_consumables),
        silver_consumables=_names(*silver_consumables),
        bronze_consumables=_names(*bronze_consumables),
        banned_consumables=_names(*banned_consumables),
        gold_planets=_names(*gold_planets),
        silver_planets=_names(*silver_planets),
        bronze_planets=_names(*bronze_planets),
        banned_planets=_names(*banned_planets),
        gold_vouchers=_names(*gold_vouchers),
        silver_vouchers=_names(*silver_vouchers),
        bronze_vouchers=_names(*bronze_vouchers),
        banned_vouchers=_names(*banned_vouchers),
        preferred_suits=tuple(preferred_suits),
        preferred_enhancements=tuple(preferred_enhancements),
        preferred_seals=tuple(preferred_seals),
        preferred_editions=tuple(preferred_editions),
        preferred_ranks=tuple(preferred_ranks),
        face_mode=face_mode,
        any_suit_concentration=bool(any_suit_concentration),
        required_jokers=_joker_names(*required_jokers),
        minimum_positive_jokers=int(minimum_positive_jokers),
        entry_evidence_cap=float(entry_evidence_cap),
    )


UNIVERSAL_BALATRO_STRATEGIES = MappingProxyType(
    {
        # Poker-hand strategies.
        "high_card": _strategy(
            "high_card",
            "High Card",
            "HIGH_CARD",
            gold_jokers=("Stuntman", "Mime", "Burnt Joker"),
            silver_jokers=(
                "Half Joker", "Supernova", "Card Sharp", "Space Joker",
                "Green Joker", "Blackboard", "Shoot the Moon", "Raised Fist",
                "Troubadour", "Juggler",
            ),
            bronze_jokers=(
                "Banner", "Delayed Gratification", "Burglar",
                "Reserved Parking", "Ramen",
            ),
            banned_jokers=(
                "Jolly Joker", "Sly Joker", "Mad Joker", "Clever Joker",
                "Zany Joker", "Wily Joker", "Crazy Joker", "Devious Joker",
                "Droll Joker", "Crafty Joker", "Runner", "Spare Trousers",
                "The Duo", "The Trio", "The Family", "The Order", "The Tribe",
            ),
            silver_consumables=("The Chariot", "Death", "The Hanged Man"),
            gold_planets=("Pluto",),
        ),
        "pair": _strategy(
            "pair",
            "Pair",
            "PAIR",
            gold_jokers=("The Duo", "Half Joker"),
            silver_jokers=(
                "Jolly Joker", "Sly Joker", "Supernova", "Card Sharp",
                "Space Joker", "Burnt Joker", "DNA", "Green Joker",
            ),
            bronze_jokers=("Blackboard", "Raised Fist", "Shoot the Moon"),
            banned_jokers=(
                "Mad Joker", "Clever Joker", "Spare Trousers", "The Trio",
                "Zany Joker", "Wily Joker", "The Family", "The Order", "Runner",
                "Crazy Joker", "Devious Joker", "The Tribe", "Droll Joker",
                "Crafty Joker",
            ),
            silver_consumables=("Death", "Strength", "Cryptid", "Ouija"),
            gold_planets=("Mercury",),
        ),
        "two_pair": _strategy(
            "two_pair",
            "Two Pair",
            "TWO_PAIR",
            gold_jokers=("Spare Trousers", "Square Joker", "The Duo"),
            silver_jokers=(
                "Mad Joker", "Clever Joker", "Jolly Joker", "Sly Joker",
                "Supernova", "Card Sharp", "Burnt Joker", "Space Joker",
            ),
            bronze_jokers=("DNA", "Trading Card"),
            banned_jokers=(
                "Half Joker", "The Trio", "Zany Joker", "Wily Joker",
                "The Family", "The Order", "Runner", "Crazy Joker",
                "Devious Joker", "The Tribe", "Droll Joker", "Crafty Joker",
            ),
            silver_consumables=("Death", "Strength", "Cryptid"),
            gold_planets=("Uranus",),
        ),
        "three_kind": _strategy(
            "three_kind",
            "Three of a Kind",
            "THREE_OF_A_KIND",
            gold_jokers=("The Trio", "The Duo", "DNA", "Half Joker"),
            silver_jokers=(
                "Zany Joker", "Wily Joker", "Jolly Joker", "Sly Joker",
                "Supernova", "Card Sharp", "Burnt Joker", "Space Joker",
            ),
            bronze_jokers=("Trading Card",),
            banned_jokers=(
                "Square Joker", "Spare Trousers", "Mad Joker", "Clever Joker",
                "The Family", "The Order", "Runner", "Crazy Joker",
                "Devious Joker", "The Tribe", "Droll Joker", "Crafty Joker",
            ),
            silver_consumables=("Death", "Strength", "Cryptid", "Ouija"),
            gold_planets=("Venus",),
        ),
        "straight": _strategy(
            "straight",
            "Straight",
            "STRAIGHT",
            gold_jokers=("Shortcut", "Four Fingers", "Runner", "The Order"),
            silver_jokers=(
                "Crazy Joker", "Devious Joker", "Superposition", "Supernova",
                "Card Sharp", "Space Joker", "Burnt Joker",
            ),
            bronze_jokers=("Fibonacci",),
            banned_jokers=(
                "Marble Joker", "Stone Joker", "The Duo", "The Trio",
                "The Family", "Spare Trousers", "Mad Joker", "Clever Joker",
                "The Tribe",
            ),
            silver_consumables=("Strength", "Death", "The Hanged Man"),
            gold_planets=("Saturn",),
        ),
        "flush": _strategy(
            "flush",
            "Flush",
            "FLUSH",
            gold_jokers=("The Tribe", "Smeared Joker", "Four Fingers"),
            silver_jokers=(
                "Droll Joker", "Crafty Joker", "Castle", "Ancient Joker",
                "Greedy Joker", "Lusty Joker", "Wrathful Joker",
                "Gluttonous Joker", "Arrowhead", "Bloodstone", "Onyx Agate",
                "Rough Gem",
            ),
            bronze_jokers=("Seeing Double",),
            banned_jokers=(
                "The Order", "Runner", "Crazy Joker", "Devious Joker",
                "The Family",
            ),
            gold_consumables=("The Star", "The Moon", "The Sun", "The World", "Sigil"),
            silver_consumables=("Death", "The Hanged Man"),
            gold_planets=("Jupiter",),
            any_suit_concentration=True,
        ),
        "full_house": _strategy(
            "full_house",
            "Full House",
            "FULL_HOUSE",
            gold_jokers=("The Duo", "The Trio"),
            silver_jokers=(
                "Jolly Joker", "Sly Joker", "Zany Joker", "Wily Joker",
                "Mad Joker", "Clever Joker", "Spare Trousers", "Supernova",
                "Card Sharp", "Burnt Joker", "Space Joker", "DNA",
            ),
            bronze_jokers=("Trading Card",),
            banned_jokers=(
                "Half Joker", "Square Joker", "The Family", "The Order", "Runner",
                "Crazy Joker", "Devious Joker", "The Tribe", "Droll Joker",
                "Crafty Joker",
            ),
            silver_consumables=("Death", "Strength", "Cryptid"),
            gold_planets=("Earth",),
            minimum_positive_jokers=2,
        ),
        "four_kind": _strategy(
            "four_kind",
            "Four of a Kind",
            "FOUR_OF_A_KIND",
            gold_jokers=("The Family", "The Trio", "The Duo", "DNA"),
            silver_jokers=(
                "Zany Joker", "Wily Joker", "Jolly Joker", "Sly Joker",
                "Square Joker", "Supernova", "Card Sharp", "Burnt Joker",
                "Space Joker",
            ),
            bronze_jokers=("Trading Card",),
            banned_jokers=(
                "Half Joker", "Spare Trousers", "Mad Joker", "Clever Joker",
                "The Order", "Runner", "Crazy Joker", "Devious Joker",
                "The Tribe", "Droll Joker", "Crafty Joker",
            ),
            gold_consumables=("Cryptid", "Ouija"),
            silver_consumables=("Death", "The Hanged Man"),
            gold_planets=("Mars",),
        ),
        "straight_flush": _strategy(
            "straight_flush",
            "Straight Flush",
            "STRAIGHT_FLUSH",
            gold_jokers=(
                "The Order", "The Tribe", "Four Fingers", "Shortcut",
                "Smeared Joker", "Seance",
            ),
            silver_jokers=(
                "Runner", "Crazy Joker", "Devious Joker", "Droll Joker",
                "Crafty Joker", "Castle", "Ancient Joker",
            ),
            bronze_jokers=("Arrowhead", "Bloodstone", "Onyx Agate", "Rough Gem"),
            banned_jokers=(
                "Marble Joker", "Stone Joker", "DNA", "The Family",
                "Spare Trousers",
            ),
            gold_consumables=("The Star", "The Moon", "The Sun", "The World", "Sigil"),
            silver_consumables=("Strength", "Death"),
            gold_planets=("Neptune",),
            any_suit_concentration=True,
            minimum_positive_jokers=2,
        ),
        "five_kind": _strategy(
            "five_kind",
            "Five of a Kind",
            "FIVE_OF_A_KIND",
            gold_jokers=("The Family", "The Trio", "The Duo", "DNA"),
            silver_jokers=(
                "Zany Joker", "Wily Joker", "Jolly Joker", "Sly Joker",
                "Supernova", "Card Sharp", "Burnt Joker", "Space Joker",
                "The Idol",
            ),
            bronze_jokers=("Trading Card",),
            banned_jokers=(
                "Half Joker", "Square Joker", "The Order", "Runner",
                "Crazy Joker", "Devious Joker", "The Tribe", "Droll Joker",
                "Crafty Joker",
            ),
            gold_consumables=("Cryptid", "Ouija"),
            silver_consumables=("Death", "The Hanged Man"),
            gold_planets=("Planet X",),
            minimum_positive_jokers=2,
        ),
        "flush_house": _strategy(
            "flush_house",
            "Flush House",
            "FLUSH_HOUSE",
            gold_jokers=("The Tribe", "The Trio", "The Duo", "Smeared Joker"),
            silver_jokers=(
                "Droll Joker", "Crafty Joker", "Zany Joker", "Wily Joker",
                "Jolly Joker", "Sly Joker", "Mad Joker", "Clever Joker",
                "Spare Trousers", "Castle", "Ancient Joker", "Arrowhead",
                "Bloodstone", "Onyx Agate", "Rough Gem",
            ),
            bronze_jokers=("DNA", "Trading Card"),
            banned_jokers=(
                "Half Joker", "Square Joker", "The Family", "The Order", "Runner",
                "Crazy Joker", "Devious Joker",
            ),
            gold_consumables=("The Star", "The Moon", "The Sun", "The World", "Sigil"),
            silver_consumables=("Death", "Cryptid"),
            gold_planets=("Ceres",),
            any_suit_concentration=True,
            minimum_positive_jokers=2,
        ),
        "flush_five": _strategy(
            "flush_five",
            "Flush Five",
            "FLUSH_FIVE",
            gold_jokers=("The Tribe", "The Family", "The Trio", "The Duo", "DNA", "The Idol"),
            silver_jokers=(
                "Zany Joker", "Wily Joker", "Jolly Joker", "Sly Joker",
                "Droll Joker", "Crafty Joker", "Arrowhead", "Bloodstone",
                "Onyx Agate", "Rough Gem", "Supernova", "Card Sharp",
            ),
            bronze_jokers=("Smeared Joker", "Trading Card"),
            banned_jokers=(
                "Half Joker", "Square Joker", "The Order", "Runner",
                "Crazy Joker", "Devious Joker",
            ),
            gold_consumables=("Cryptid", "Ouija"),
            silver_consumables=("Death", "The Star", "The Moon", "The Sun", "The World", "Sigil"),
            gold_planets=("Eris",),
            any_suit_concentration=True,
            minimum_positive_jokers=2,
        ),

        # Mechanic and suit strategies.
        "face_cards": _strategy(
            "face_cards",
            "Face Cards",
            gold_jokers=("Triboulet", "Sock and Buskin", "Photograph", "Pareidolia"),
            silver_jokers=(
                "Scary Face", "Smiley Face", "Business Card", "Midas Mask",
                "Hanging Chad",
            ),
            bronze_jokers=("Reserved Parking",),
            banned_jokers=("Ride the Bus", "Faceless Joker"),
            silver_consumables=("Strength", "Death", "The Hanged Man", "Familiar"),
            preferred_ranks=("J", "Q", "K"),
            face_mode="FACE",
        ),
        "faceless": _strategy(
            "faceless",
            "Faceless / No-Face",
            gold_jokers=("Ride the Bus",),
            silver_jokers=(
                "Faceless Joker", "Hack", "Fibonacci", "Even Steven",
                "Odd Todd", "Wee Joker",
            ),
            bronze_jokers=("Walkie Talkie",),
            banned_jokers=(
                "Pareidolia", "Triboulet", "Sock and Buskin", "Photograph",
                "Scary Face", "Smiley Face", "Business Card", "Baron",
                "Shoot the Moon", "Hit the Road", "Reserved Parking", "Midas Mask",
            ),
            silver_consumables=("The Hanged Man", "Death", "Immolate", "Incantation"),
            face_mode="NO_FACE",
        ),
        "hearts": _strategy(
            "hearts",
            "Hearts",
            gold_jokers=("Bloodstone", "Smeared Joker"),
            silver_jokers=("Lusty Joker", "Hanging Chad", "Seltzer", "Dusk"),
            bronze_jokers=("Ancient Joker",),
            banned_jokers=("Wrathful Joker", "Gluttonous Joker", "Arrowhead", "Onyx Agate"),
            gold_consumables=("The Sun",),
            silver_consumables=("The Lovers", "Death", "The Hanged Man", "Sigil"),
            preferred_suits=("Hearts",),
        ),
        "diamonds": _strategy(
            "diamonds",
            "Diamonds",
            gold_jokers=("Rough Gem", "Smeared Joker"),
            silver_jokers=("Greedy Joker", "Hanging Chad", "Seltzer", "Dusk"),
            bronze_jokers=("Ancient Joker",),
            banned_jokers=("Wrathful Joker", "Gluttonous Joker", "Arrowhead", "Onyx Agate"),
            gold_consumables=("The Star",),
            silver_consumables=("The Lovers", "Death", "The Hanged Man", "Sigil"),
            preferred_suits=("Diamonds",),
        ),
        "clubs": _strategy(
            "clubs",
            "Clubs",
            gold_jokers=("Onyx Agate", "Seeing Double", "Smeared Joker"),
            silver_jokers=("Gluttonous Joker", "Blackboard", "Hanging Chad", "Seltzer", "Dusk"),
            bronze_jokers=("Ancient Joker",),
            banned_jokers=("Lusty Joker", "Greedy Joker", "Bloodstone", "Rough Gem"),
            gold_consumables=("The Moon",),
            silver_consumables=("The Lovers", "Death", "The Hanged Man", "Sigil"),
            preferred_suits=("Clubs",),
        ),
        "spades": _strategy(
            "spades",
            "Spades",
            gold_jokers=("Arrowhead", "Smeared Joker"),
            silver_jokers=("Wrathful Joker", "Blackboard", "Hanging Chad", "Seltzer", "Dusk"),
            bronze_jokers=("Ancient Joker",),
            banned_jokers=("Lusty Joker", "Greedy Joker", "Bloodstone", "Rough Gem"),
            gold_consumables=("The World",),
            silver_consumables=("The Lovers", "Death", "The Hanged Man", "Sigil"),
            preferred_suits=("Spades",),
        ),
        "glass": _strategy(
            "glass",
            "Glass",
            gold_jokers=("Glass Joker", "Hanging Chad"),
            silver_jokers=("Dusk", "Seltzer", "Sock and Buskin", "Hack", "DNA"),
            bronze_jokers=("Hologram",),
            banned_jokers=("Vampire", "Midas Mask", "Marble Joker"),
            gold_consumables=("Justice",),
            silver_consumables=("Death", "Cryptid", "Ankh"),
            preferred_enhancements=("Glass",),
        ),
        "steel": _strategy(
            "steel",
            "Steel",
            gold_jokers=("Steel Joker", "Mime"),
            silver_jokers=(
                "Shoot the Moon", "Blackboard", "Troubadour", "Juggler",
                "Raised Fist", "Reserved Parking", "DNA",
            ),
            bronze_jokers=("Turtle Bean",),
            banned_jokers=("Vampire", "Midas Mask"),
            gold_consumables=("The Chariot",),
            silver_consumables=("Death", "Cryptid", "Trance"),
            preferred_enhancements=("Steel",),
        ),
        "lucky": _strategy(
            "lucky",
            "Lucky",
            gold_jokers=("Lucky Cat", "Oops All 6s", "Hanging Chad"),
            silver_jokers=("Dusk", "Seltzer", "Sock and Buskin", "Hack", "DNA"),
            bronze_jokers=("Business Card",),
            banned_jokers=("Vampire", "Midas Mask"),
            gold_consumables=("The Magician",),
            silver_consumables=("Death", "Cryptid"),
            preferred_enhancements=("Lucky",),
        ),
        "stone": _strategy(
            "stone",
            "Stone",
            gold_jokers=("Stone Joker", "Marble Joker"),
            silver_jokers=("Hologram", "Driver's License", "DNA", "Blue Joker"),
            bronze_jokers=("Certificate",),
            banned_jokers=(
                "Vampire", "Erosion", "The Order", "Runner", "Crazy Joker",
                "Devious Joker", "The Tribe", "Droll Joker", "Crafty Joker",
                "Greedy Joker", "Lusty Joker", "Wrathful Joker", "Gluttonous Joker",
                "Arrowhead", "Bloodstone", "Onyx Agate", "Rough Gem", "Scholar",
                "Fibonacci", "Hack", "Even Steven", "Odd Todd",
            ),
            gold_consumables=("The Tower",),
            silver_consumables=("Death", "Cryptid"),
            preferred_enhancements=("Stone",),
        ),
        "gold_cards": _strategy(
            "gold_cards",
            "Gold Cards",
            gold_jokers=("Golden Ticket", "Midas Mask", "Mime"),
            silver_jokers=(
                "Hanging Chad", "Dusk", "Seltzer", "Sock and Buskin",
                "Business Card", "Reserved Parking", "Bull", "Bootstraps",
            ),
            bronze_jokers=("To the Moon", "Rocket", "Cloud 9", "Golden Joker"),
            banned_jokers=("Vampire",),
            gold_consumables=("The Devil",),
            silver_consumables=("Death", "Cryptid"),
            preferred_enhancements=("Gold",),
        ),
        "blue_seal": _strategy(
            "blue_seal",
            "Blue Seal",
            gold_jokers=("Constellation", "Satellite"),
            silver_jokers=("Certificate", "Perkeo"),
            bronze_jokers=("Astronomer",),
            gold_consumables=("Trance",),
            silver_consumables=("Death", "Cryptid"),
            preferred_seals=("Blue",),
        ),
        "purple_seal": _strategy(
            "purple_seal",
            "Purple Seal",
            gold_jokers=("Fortune Teller", "Merry Andy", "Drunkard"),
            silver_jokers=(
                "Burnt Joker", "Castle", "Mail-In Rebate", "Faceless Joker",
                "Mystic Summit", "Certificate", "Cartomancer",
            ),
            bronze_jokers=("Vagabond", "Hallucination", "Perkeo"),
            banned_jokers=("Burglar", "Delayed Gratification", "Green Joker", "Ramen", "Banner"),
            gold_consumables=("The Medium",),
            silver_consumables=("Death", "Cryptid"),
            preferred_seals=("Purple",),
        ),
        "red_seal": _strategy(
            "red_seal",
            "Red Seal",
            gold_jokers=("Hanging Chad", "Mime"),
            silver_jokers=(
                "Seltzer", "Dusk", "Sock and Buskin", "Hack", "Bloodstone",
                "Triboulet", "Photograph", "Baron", "Steel Joker", "Lucky Cat",
            ),
            bronze_jokers=("Scary Face", "Smiley Face", "Business Card"),
            gold_consumables=("Deja Vu",),
            silver_consumables=("Death", "Cryptid"),
            preferred_seals=("Red",),
        ),
        "gold_seal": _strategy(
            "gold_seal",
            "Gold Seal",
            gold_jokers=("Hanging Chad", "Seltzer", "Dusk"),
            silver_jokers=(
                "Sock and Buskin", "Hack", "Bull", "Bootstraps", "To the Moon",
                "Rocket", "Cloud 9", "Golden Joker", "Certificate",
            ),
            bronze_jokers=("Business Card",),
            gold_consumables=("Talisman",),
            silver_consumables=("Death", "Cryptid"),
            preferred_seals=("Gold",),
        ),
        "edition": _strategy(
            "edition",
            "Edition",
            gold_jokers=("Abstract Joker", "Baseball Card"),
            silver_jokers=("Swashbuckler", "Riff-Raff", "Ceremonial Dagger"),
            gold_consumables=("Aura", "Ectoplasm", "Hex"),
            silver_consumables=("The Wheel of Fortune",),
            preferred_editions=("Foil", "Holographic", "Polychrome", "Negative"),
        ),

        # Niche/synergy strategies.
        "aces": _strategy(
            "aces",
            "Aces",
            gold_jokers=("Scholar", "DNA"),
            silver_jokers=("Fibonacci", "Odd Todd", "Superposition", "The Idol"),
            bronze_jokers=("Hologram",),
            banned_jokers=(
                "Even Steven", "Walkie Talkie", "Hack", "Wee Joker", "Baron",
                "Shoot the Moon", "Hit the Road",
            ),
            gold_consumables=("Grim",),
            silver_consumables=("Death", "Strength", "Cryptid"),
            preferred_ranks=("A",),
        ),
        "flower_pot": _strategy(
            "flower_pot",
            "Smeared / Splash + Flower Pot",
            gold_jokers=("Flower Pot", "Smeared Joker", "Splash"),
            silver_jokers=(
                "Seeing Double", "Ancient Joker", "Arrowhead", "Bloodstone",
                "Onyx Agate", "Rough Gem",
            ),
            bronze_jokers=("Greedy Joker", "Lusty Joker", "Wrathful Joker", "Gluttonous Joker"),
            banned_jokers=("The Tribe", "Droll Joker", "Crafty Joker"),
            gold_consumables=("The Lovers", "Sigil"),
            silver_consumables=("The Star", "The Moon", "The Sun", "The World", "Death"),
            minimum_positive_jokers=2,
        ),
        "canio_destruction": _strategy(
            "canio_destruction",
            "Canio Destruction",
            gold_jokers=("Canio", "Pareidolia", "Trading Card"),
            silver_jokers=("Sixth Sense", "Glass Joker"),
            bronze_jokers=("Faceless Joker",),
            banned_jokers=(
                "Triboulet", "Sock and Buskin", "Photograph", "Scary Face",
                "Smiley Face", "Business Card", "Baron", "Shoot the Moon",
                "Hit the Road", "Reserved Parking", "Ride the Bus",
            ),
            gold_consumables=("The Hanged Man", "Immolate"),
            silver_consumables=("Familiar", "Grim", "Incantation", "Death"),
            required_jokers=("Canio",),
        ),
        "vampire": _strategy(
            "vampire",
            "Vampire",
            gold_jokers=("Vampire", "Midas Mask", "Pareidolia"),
            silver_jokers=("Cartomancer", "Vagabond", "Hallucination", "DNA", "Marble Joker"),
            bronze_jokers=("Fortune Teller",),
            banned_jokers=(
                "Steel Joker", "Glass Joker", "Lucky Cat", "Stone Joker",
                "Golden Ticket", "Driver's License",
            ),
            gold_consumables=(
                "The Magician", "The Empress", "The Hierophant", "The Lovers",
                "The Chariot", "Justice", "The Devil", "The Tower",
            ),
            silver_consumables=("Familiar", "Grim", "Incantation"),
            required_jokers=("Vampire",),
        ),
    }
)
